// <auto-generated />
using System;
using MTLCRISTALVK18BACK.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MTLCRISTALVK18BACK.Migrations
{
    [DbContext(typeof(MTLCRISTALContexts))]
    [Migration("20250421202020_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MTLCRISTALVK18BACK.Models.Habitaciones.Habitaciones", b =>
                {
                    b.Property<int>("IdHbtn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHbtn"), 1L, 1);

                    b.Property<string>("AcargoUserMTL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Albercahab")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diasemofinhab")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estadohab")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Folioordenhab")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jacuzzihab")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Limpiezahab")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numhab")
                        .HasColumnType("int");

                    b.Property<string>("Preciohab")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statushab")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tiemporenthab")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoCamahab")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipohab")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TurnoUserMTL")
                        .HasColumnType("int");

                    b.HasKey("IdHbtn");

                    b.ToTable("Habitaciones");
                });

            modelBuilder.Entity("MTLCRISTALVK18BACK.Models.Reservas.Reservas", b =>
                {
                    b.Property<int>("IdResv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdResv"), 1L, 1);

                    b.Property<string>("AcargoUserMTL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diasemofinresv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estadoresv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Folioordenresv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Horarentaresv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Limpiezahabresv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numresv")
                        .HasColumnType("int");

                    b.Property<string>("Precioresv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statushabresv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statuspagohabresv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tiemporentresv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tiporesv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TurnoUserMTL")
                        .HasColumnType("int");

                    b.HasKey("IdResv");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("MTLCRISTALVK18BACK.Models.Reservas.Tipo1Cliente", b =>
                {
                    b.Property<int>("IdClte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClte"), 1L, 1);

                    b.Property<string>("AcargoUserMTL1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdvertCl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AutColorCl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AutMarcaCl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AutPlacasCl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaEntradaCl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaSalidaCl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrecuenciaCl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumHabCl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReservasIdResv")
                        .HasColumnType("int");

                    b.Property<string>("StatusingresoCl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalConsumos")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdClte");

                    b.HasIndex("ReservasIdResv");

                    b.ToTable("Tipo1Cliente");
                });

            modelBuilder.Entity("MTLCRISTALVK18BACK.Models.Reservas.Tipo2Consumos", b =>
                {
                    b.Property<int>("IdCsms")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCsms"), 1L, 1);

                    b.Property<string>("AcargoUserMTL2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cantidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrecioUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReservasIdResv")
                        .HasColumnType("int");

                    b.Property<string>("StatusPagado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Totalconsumos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Totalpagado")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCsms");

                    b.HasIndex("ReservasIdResv");

                    b.ToTable("Tipo2Consumos");
                });

            modelBuilder.Entity("MTLCRISTALVK18BACK.Models.Usersadmin.Usersadmin", b =>
                {
                    b.Property<int>("IdUs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUs"), 1L, 1);

                    b.Property<string>("DepartamentoUs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailUs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NtrabajadorUs")
                        .HasColumnType("int");

                    b.Property<string>("PasswordUs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PuestoUs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsernameUs")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUs");

                    b.ToTable("Usersadmin");
                });

            modelBuilder.Entity("MTLCRISTALVK18BACK.Models.Reservas.Tipo1Cliente", b =>
                {
                    b.HasOne("MTLCRISTALVK18BACK.Models.Reservas.Reservas", null)
                        .WithMany("Tipo1ResvdCl")
                        .HasForeignKey("ReservasIdResv")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MTLCRISTALVK18BACK.Models.Reservas.Tipo2Consumos", b =>
                {
                    b.HasOne("MTLCRISTALVK18BACK.Models.Reservas.Reservas", null)
                        .WithMany("Tipo2ResvdCl")
                        .HasForeignKey("ReservasIdResv")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MTLCRISTALVK18BACK.Models.Reservas.Reservas", b =>
                {
                    b.Navigation("Tipo1ResvdCl");

                    b.Navigation("Tipo2ResvdCl");
                });
#pragma warning restore 612, 618
        }
    }
}
