// <auto-generated />
using System;
using MTLCRISTALVK18BACK.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MTLCRISTALVK18BACK.Migrations
{
    [DbContext(typeof(MTLCRISTALContexts))]
    [Migration("20260904031841_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MTLCRISTALVK18BACK.Models.Habitaciones.Habitaciones", b =>
                {
                    b.Property<int>("IdHbtn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHbtn"), 1L, 1);

                    b.Property<string>("AcargoUserMTL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Albercahab")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diasemofinhab")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estadohab")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Folioordenhab")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jacuzzihab")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Limpiezahab")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numhab")
                        .HasColumnType("int");

                    b.Property<string>("Preciohab")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statushab")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tiemporenthab")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoCamahab")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipohab")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TurnoUserMTL")
                        .HasColumnType("int");

                    b.HasKey("IdHbtn");

                    b.ToTable("Habitaciones");
                });

            modelBuilder.Entity("MTLCRISTALVK18BACK.Models.Reservas.ReservaCliente", b =>
                {
                    b.Property<int>("IdClte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClte"), 1L, 1);

                    b.Property<string>("AdvertCl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("AutColorCl")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AutMarcaCl")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("AutModeloCl")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("AutPlacasCl")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("FrecuenciaCl")
                        .HasColumnType("int");

                    b.Property<int>("IdResv")
                        .HasColumnType("int");

                    b.Property<string>("NombreCliente")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("StatusingresoCl")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdClte");

                    b.HasIndex("IdResv")
                        .IsUnique();

                    b.ToTable("ReservaClientes");
                });

            modelBuilder.Entity("MTLCRISTALVK18BACK.Models.Reservas.ReservaConsumo", b =>
                {
                    b.Property<int>("IdCsms")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCsms"), 1L, 1);

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EstadoPedido")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset?>("FechaEntrega")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaSolicitud")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("IdResv")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsEntrega")
                        .HasColumnType("int");

                    b.Property<int>("IdUsRegistro")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("int");

                    b.Property<string>("StatusPagado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("TotalLinea")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdCsms");

                    b.HasIndex("IdUsEntrega");

                    b.HasIndex("IdUsRegistro");

                    b.HasIndex("IdResv", "EstadoPedido");

                    b.ToTable("ReservaConsumos");
                });

            modelBuilder.Entity("MTLCRISTALVK18BACK.Models.Reservas.Reservas", b =>
                {
                    b.Property<int>("IdResv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdResv"), 1L, 1);

                    b.Property<string>("Estadoresv")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("FechaHoraEntrada")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaHoraSalidaProgramada")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaHoraSalidaReal")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Folioordenresv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdHbtn")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsCierre")
                        .HasColumnType("int");

                    b.Property<int>("IdUsRegistro")
                        .HasColumnType("int");

                    b.Property<int>("Numresv")
                        .HasColumnType("int");

                    b.Property<decimal>("Precioresv")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Statuspagohabresv")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("TiempoRentaMinutos")
                        .HasColumnType("int");

                    b.Property<string>("Tiporesv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalConsumos")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalReserva")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TurnoUserMTL")
                        .HasColumnType("int");

                    b.HasKey("IdResv");

                    b.HasIndex("Estadoresv");

                    b.HasIndex("IdHbtn");

                    b.HasIndex("IdUsCierre");

                    b.HasIndex("IdUsRegistro");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("MTLCRISTALVK18BACK.Models.Usersadmin.Usersadmin", b =>
                {
                    b.Property<int>("IdUs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUs"), 1L, 1);

                    b.Property<string>("DepartamentoUs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailUs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NtrabajadorUs")
                        .HasColumnType("int");

                    b.Property<string>("PasswordUs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PuestoUs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsernameUs")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUs");

                    b.ToTable("Usersadmin");
                });

            modelBuilder.Entity("MTLCRISTALVK18BACK.Models.Reservas.ReservaCliente", b =>
                {
                    b.HasOne("MTLCRISTALVK18BACK.Models.Reservas.Reservas", "Reserva")
                        .WithOne("Cliente")
                        .HasForeignKey("MTLCRISTALVK18BACK.Models.Reservas.ReservaCliente", "IdResv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("MTLCRISTALVK18BACK.Models.Reservas.ReservaConsumo", b =>
                {
                    b.HasOne("MTLCRISTALVK18BACK.Models.Reservas.Reservas", "Reserva")
                        .WithMany("Consumos")
                        .HasForeignKey("IdResv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MTLCRISTALVK18BACK.Models.Usersadmin.Usersadmin", "UsuarioEntrega")
                        .WithMany()
                        .HasForeignKey("IdUsEntrega")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MTLCRISTALVK18BACK.Models.Usersadmin.Usersadmin", "UsuarioRegistro")
                        .WithMany()
                        .HasForeignKey("IdUsRegistro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reserva");

                    b.Navigation("UsuarioEntrega");

                    b.Navigation("UsuarioRegistro");
                });

            modelBuilder.Entity("MTLCRISTALVK18BACK.Models.Reservas.Reservas", b =>
                {
                    b.HasOne("MTLCRISTALVK18BACK.Models.Habitaciones.Habitaciones", "Habitacion")
                        .WithMany()
                        .HasForeignKey("IdHbtn")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTLCRISTALVK18BACK.Models.Usersadmin.Usersadmin", "UsuarioCierre")
                        .WithMany()
                        .HasForeignKey("IdUsCierre")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MTLCRISTALVK18BACK.Models.Usersadmin.Usersadmin", "UsuarioRegistro")
                        .WithMany()
                        .HasForeignKey("IdUsRegistro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Habitacion");

                    b.Navigation("UsuarioCierre");

                    b.Navigation("UsuarioRegistro");
                });

            modelBuilder.Entity("MTLCRISTALVK18BACK.Models.Reservas.Reservas", b =>
                {
                    b.Navigation("Cliente");

                    b.Navigation("Consumos");
                });
#pragma warning restore 612, 618
        }
    }
}
